### ISSUE TITLE
No dependencies set in `requirements-all.txt`

### ISSUE THREAD

**Issue by ludelafo** [swiss-ai-center/create-a-new-service-generic-template#4]
The [`requirements-all.txt`](https://github.com/swiss-ai-center/create-a-new-service-generic-template/blob/main/requirements-all.txt) doesn't contain any dependencies. Is this expected?

This is the same for the [create-a-new-service-model-from-scratch-template](https://github.com/swiss-ai-center/create-a-new-service-model-from-scratch-template) repository.

**Comment by andrptrc** [comment]
Removed file
